### ISSUE TITLE
non coding related issues

### ISSUE THREAD

**Issue by KhunakornP** [NapatrSaengthongsakullert/ku-polls#13]
A list detailing non coding related issues

readme.MD
- [ ]  Django tutorial link does not exists
- [ ]  Installation guide section does not link to Installation.MD
- [ ] No Users section in readme

Installation.MD
- [ ] Installation instructions uses both windows and mac/linux syntax
- [ ] Installation instructions for .env does not have ALLOWED_HOSTS variable

wiki
- [ ] Project plan incomplete missing: Schedule and goal for iteration2,3,4 in Project Plan page.

Suggestions:
- add super user to the User section as well'
- UI needs a lot of improvement
- Question choices for some questions like : What's the best programing language to learn first? could use some work (more choices)

**Comment by NapatrSaengthongsakullert** [comment]
A list detailing non coding related issues

readme.MD

 **FIXED** Django tutorial link does not exists
 **FIXED** Installation guide section does not link to Installation.MD
 **FIXED** No Users section in readme

Installation.MD

 **FIXED** Installation instructions uses both windows and mac/linux syntax
**FIXED**  Installation instructions for .env does not have ALLOWED_HOSTS variable

wiki

 **FIXED** Project plan incomplete missing: Schedule and goal for iteration2,3,4 in Project Plan page.

Suggestions:

**FIXED**  add super user to the User section as well'
**DOING** UI needs a lot of improvement
**FIXED** Question choices for some questions like : What's the best programing language to learn first? could use some work (more choices)
