### ISSUE TITLE
Polls does not redirect user back to index page on bad URL

### ISSUE THREAD

**Issue by KhunakornP** [NapatrSaengthongsakullert/ku-polls#15]
The application does not redirect the user back to the index page on an invalid question such as http://127.0.0.1:8000/polls/99/
same with the results page

**Comment by NapatrSaengthongsakullert** [comment]
**FIXED** The application does not redirect the user back to the index page on an invalid question such as http://127.0.0.1:8000/polls/99/
same with the results page
