### ISSUE TITLE
Results page contains Vote again?

### ISSUE THREAD

**Issue by KhunakornP** [NapatrSaengthongsakullert/ku-polls#16]
The results page has a vote again link despite the user being allowed 1 vote per question
![vote req](https://github.com/user-attachments/assets/ee4450f6-8e82-458b-82d9-88d352b6ac35)
![vote req-2](https://github.com/user-attachments/assets/5966d88d-662a-450b-8fc2-2745321f1ce6)

**Comment by NapatrSaengthongsakullert** [comment]
**FIXED** The results page has a vote again link despite the user being allowed 1 vote per question

**Comment by NapatrSaengthongsakullert** [comment]
**FIXED** The results page has a vote again link despite the user being allowed 1 vote per question
